/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TalentScoutGlobal;

import ui.PhysicalTraining.*;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.TalentRecruitmentOrganization;
import business.Organization.TalentScoutOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import business.WorkQueue.TalentScoutWorkRequest;
/**
 *
 * @author puranjaimendiratta
 */
public class EnrollmentFormJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentFormJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    TalentScoutOrganization organization;
    Network network;
    public EnrollmentFormJPanel(JPanel userProcessContainer, EcoSystem system,UserAccount userAccount,Organization organization, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = (TalentScoutOrganization) organization;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        namesurvivorjLabel = new javax.swing.JLabel();
        relationjLabel = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        lblNameofSuspect = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        friendRadioButton = new javax.swing.JRadioButton();
        parentRadioButton = new javax.swing.JRadioButton();
        txtSuspectName = new javax.swing.JTextField();
        txtMoreDetails = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        ReportjButton = new javax.swing.JButton();
        comboBoxIncident = new javax.swing.JComboBox<>();
        txtAgeofChild = new javax.swing.JTextField();
        lblAgeofChild = new javax.swing.JLabel();
        dateOfIncident = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namesurvivorjLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        namesurvivorjLabel.setText("Name of Child : ");
        jPanel2.add(namesurvivorjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 135, -1));

        relationjLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        relationjLabel.setText("                Gender : ");
        jPanel2.add(relationjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 210, -1));

        lblType.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblType.setText("         Sport :");
        jPanel2.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 142, 20));

        lblLocation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblLocation.setText("            Address : ");
        jPanel2.add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 180, -1));

        lblDate.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDate.setText("Date of Enrollment :");
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 170, 20));

        lblDetails.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDetails.setText("Parent Name :");
        jPanel2.add(lblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 110, -1));

        lblNameofSuspect.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblNameofSuspect.setText("         Weight :");
        jPanel2.add(lblNameofSuspect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 140, -1));

        txtChildName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtChildName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 230, -1));

        friendRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        friendRadioButton.setText("Female");
        friendRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(friendRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        parentRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        parentRadioButton.setText("Male");
        parentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentRadioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(parentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 58, -1));

        txtSuspectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSuspectNameActionPerformed(evt);
            }
        });
        jPanel2.add(txtSuspectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 230, -1));
        jPanel2.add(txtMoreDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 230, -1));

        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        jPanel2.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 230, 50));

        ReportjButton.setBackground(new java.awt.Color(255, 146, 1));
        ReportjButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        ReportjButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportjButton.setText("Enroll");
        ReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportjButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ReportjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 107, -1));

        comboBoxIncident.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Cricket", "Hockey", "Basket Ball", "Atheletics", "Football" }));
        comboBoxIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxIncidentActionPerformed(evt);
            }
        });
        jPanel2.add(comboBoxIncident, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));
        jPanel2.add(txtAgeofChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 230, -1));

        lblAgeofChild.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblAgeofChild.setText("Age :");
        jPanel2.add(lblAgeofChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 50, -1));
        jPanel2.add(dateOfIncident, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Fill up the enrollment form");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 844, 633));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 218, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtChildNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildNameActionPerformed

    private void parentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentRadioButtonActionPerformed

    private void ReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportjButtonActionPerformed

        TalentScoutWorkRequest request = new TalentScoutWorkRequest();
        request.setStatus("Waiting");
        request.setSender(userAccount);

        request.setChildName(txtChildName.getText());
//        request.setEmail(txtAgeofChild.getText());
        //for choosing relations
        
        if(txtAgeofChild.getText().length() > 0 ){
            if(Integer.parseInt(txtAgeofChild.getText())<=0 || Integer.parseInt(txtAgeofChild.getText()) >= 18){
                JOptionPane.showMessageDialog(this, "Child Age is not correct");
            }else{
                request.setAge(Integer.parseInt(txtAgeofChild.getText()));
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please enter an age of child");
        }
        
        if(friendRadioButton.isSelected())
        {
            request.setRelation("Female");
        }
        else if(parentRadioButton.isSelected())
        {
            request.setRelation("Male");
        }
      
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a gender");

        }
        //for choosing type
        if(comboBoxIncident.getSelectedItem().toString().equalsIgnoreCase("Select one"))
        {
            JOptionPane.showMessageDialog(null, "Please select a Sport");
        }
        else{
            request.setSportType(comboBoxIncident.getSelectedItem().toString());
        }
        //location
        request.setAddress(txtLocation.getText());
        //date
        if(dateOfIncident.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "Please select a date");
        }else{
            request.setDoe(dateOfIncident.getDate());
        }
        //more detaisl
        if(txtMoreDetails.getText()==null)
        {
            JOptionPane.showMessageDialog(null, "Please enter parent name");
            return;
        }
        request.setParentName(txtMoreDetails.getText());
        request.setWeight(txtSuspectName.getText());

        if( request.getAge() != null && request.getDoe()!=null && request.getAddress()!=null && request.getGender()!=null && request.getChildName()!=null && request.getSportType()!=null)
        {
            Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.NGO);
            Organization org = null;
            for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof TalentRecruitmentOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                org.getWorkQueue().getTalentScoutWorkRequestList().add(request);
                //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            }

            txtChildName.setText("");
            txtSuspectName.setText("");
            txtMoreDetails.setText("");
            txtLocation.setText("");
            txtAgeofChild.setText("");
            dateOfIncident.setDate(null);
            friendRadioButton.setSelected(false);
            parentRadioButton.setSelected(false);
           
            comboBoxIncident.setSelectedIndex(0);
            // dateOfIncident.setDate(null);
            userAccount.getWrkQue().getTalentScoutWorkRequestList().add(request);

            JOptionPane.showMessageDialog(null, "Enrollment completed successfully.");

        }
    }//GEN-LAST:event_ReportjButtonActionPerformed

    private void comboBoxIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxIncidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxIncidentActionPerformed

    private void friendRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friendRadioButtonActionPerformed

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtSuspectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSuspectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSuspectNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReportjButton;
    private javax.swing.JComboBox<String> comboBoxIncident;
    private com.toedter.calendar.JDateChooser dateOfIncident;
    private javax.swing.JRadioButton friendRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgeofChild;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNameofSuspect;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel namesurvivorjLabel;
    private javax.swing.JRadioButton parentRadioButton;
    private javax.swing.JLabel relationjLabel;
    private javax.swing.JTextField txtAgeofChild;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMoreDetails;
    private javax.swing.JTextField txtSuspectName;
    // End of variables declaration//GEN-END:variables
}
