/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.TalentScoutGlobal;

import business.EcoSystem;
import business.Enterprise.Enterprise;

import business.Enterprise.TalentScoutGlobalEnterprise;
import business.Organization.TalentScoutOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.TalentScoutWorkRequest;
import business.WorkQueue.FundAllocatorWorkRequest;
import business.WorkQueue.TrainingCoachWorkRequest;
import business.WorkQueue.InsuranceAgentWorkRequest;
import business.WorkQueue.MentalHealthCoachWorkRequest;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author puranjaimendiratta
 */
public class TalentScoutViewStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TalentScoutViewStatusJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private TalentScoutOrganization CROrganization; 
    private Organization organization;
    private TalentScoutGlobalEnterprise CREnterprise;
    public TalentScoutViewStatusJPanel(JPanel userProcessContainer, UserAccount account, Organization organization,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.CROrganization = (TalentScoutOrganization)organization;
        this.CREnterprise = (TalentScoutGlobalEnterprise) enterprise;
        this.organization=organization;
        
       popTable();
       popStatusTable();
       lblCaseVolunteer.setVisible(false);
       lblDate.setVisible(false);
       lblReceiver.setVisible(false);
       lblStatus.setVisible(false);
       lblCounsellor.setVisible(false);
       lblLawyer.setVisible(false);
       lblDoc.setVisible(false);
       lblPsych.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCases = new javax.swing.JTable();
        lblCaseVolunteer = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblReceiver = new javax.swing.JLabel();
        txtCaseVolunteerDate = new javax.swing.JLabel();
        txtCaseVolunteer = new javax.swing.JLabel();
        txtCaseVolunteerStatus = new javax.swing.JLabel();
        lblCounsellor = new javax.swing.JLabel();
        txtDoctorDate = new javax.swing.JLabel();
        txtDoctor = new javax.swing.JLabel();
        txtDoctorStatus = new javax.swing.JLabel();
        lblLawyer = new javax.swing.JLabel();
        lblDoc = new javax.swing.JLabel();
        lblPsych = new javax.swing.JLabel();
        txtCounsellorDate = new javax.swing.JLabel();
        txtCOunsellor = new javax.swing.JLabel();
        txtCounsellorStatus = new javax.swing.JLabel();
        txtLawyerDate = new javax.swing.JLabel();
        txtLawyer = new javax.swing.JLabel();
        txtLawyerStatus = new javax.swing.JLabel();
        txtlPsychDate = new javax.swing.JLabel();
        txtPsych = new javax.swing.JLabel();
        txtPsychStatus = new javax.swing.JLabel();
        btnCheckStatus = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Index", "Date", "Receiver ", "Current Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCases);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 0, 598, 156));

        lblCaseVolunteer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblCaseVolunteer.setForeground(new java.awt.Color(255, 146, 1));
        lblCaseVolunteer.setText("Talent Scout");
        jPanel3.add(lblCaseVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 189, 125, -1));

        lblDate.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDate.setText("Date:");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblReceiver.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblReceiver.setText("Assigned To:");
        jPanel3.add(lblReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 32));
        jPanel3.add(txtCaseVolunteerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 217, 120, 35));
        jPanel3.add(txtCaseVolunteer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 125, 32));
        jPanel3.add(txtCaseVolunteerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 320, 125, 30));

        lblCounsellor.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblCounsellor.setForeground(new java.awt.Color(255, 146, 1));
        lblCounsellor.setText("Fund Allocator");
        jPanel3.add(lblCounsellor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 103, -1));
        jPanel3.add(txtDoctorDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 100, 30));
        jPanel3.add(txtDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 90, 32));
        jPanel3.add(txtDoctorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 100, 30));

        lblLawyer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblLawyer.setForeground(new java.awt.Color(255, 146, 1));
        lblLawyer.setText("Insurance Agent");
        jPanel3.add(lblLawyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        lblDoc.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDoc.setForeground(new java.awt.Color(255, 146, 1));
        lblDoc.setText("Training Coach");
        jPanel3.add(lblDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 110, -1));

        lblPsych.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblPsych.setForeground(new java.awt.Color(255, 146, 1));
        lblPsych.setText("Health Coach");
        jPanel3.add(lblPsych, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 108, -1));
        jPanel3.add(txtCounsellorDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 120, 35));
        jPanel3.add(txtCOunsellor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 120, 32));
        jPanel3.add(txtCounsellorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, 30));
        jPanel3.add(txtLawyerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 101, 35));
        jPanel3.add(txtLawyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 103, 36));
        jPanel3.add(txtLawyerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 103, 21));
        jPanel3.add(txtlPsychDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 145, 35));
        jPanel3.add(txtPsych, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 145, 36));
        jPanel3.add(txtPsychStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 145, 21));

        btnCheckStatus.setBackground(new java.awt.Color(255, 146, 1));
        btnCheckStatus.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnCheckStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckStatus.setText("Check Status");
        btnCheckStatus.setBorderPainted(false);
        btnCheckStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckStatusMouseExited(evt);
            }
        });
        btnCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStatusActionPerformed(evt);
            }
        });
        jPanel3.add(btnCheckStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 70, -1, -1));

        lblStatus.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblStatus.setText("Status:");
        jPanel3.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 21));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 400));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -16, 940, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(354, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckStatusMouseEntered
        btnCheckStatus.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckStatusMouseEntered

    private void btnCheckStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckStatusMouseExited
        btnCheckStatus.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckStatusMouseExited

    private void btnCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStatusActionPerformed
        popStatusTable();
    }//GEN-LAST:event_btnCheckStatusActionPerformed
    
    private void popTable() {
        
        DefaultTableModel model= (DefaultTableModel) tableCases.getModel();
        Object[] row=new Object[4];
        model.setRowCount(0);
        int count = 1;
        for(TalentScoutWorkRequest request : userAccount.getWrkQue().getTalentScoutWorkRequestList())
         {
            request.setRequestid(count);
            row[0]=request.getRequestid();
            row[1] = request.getDoe();
            if (request.getReceiver()==null){
                row[2] = "Not Assigned";
            }else{
                row[2] = request.getReceiver().getEmp().getName();
            }
            row[3] = request;
            
           
            
            model.addRow(row);
            count++;
            txtCaseVolunteerDate.setText("");
            txtCaseVolunteer.setText("");
            txtCaseVolunteerStatus.setText("");
            
            
        }
        
        
    }
    
    
    private void popStatusTable() {
        int selectedRow = tableCases.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        if (selectedRow >= 0) {
            lblCaseVolunteer.setVisible(true);
            lblDate.setVisible(true);
            lblReceiver.setVisible(true);
            lblStatus.setVisible(true);
            lblCounsellor.setVisible(true);
            lblLawyer.setVisible(true);
            lblDoc.setVisible(true);
            lblPsych.setVisible(true);
            TalentScoutWorkRequest  CaseRepoWorkReq  = (TalentScoutWorkRequest) tableCases.getValueAt(selectedRow, 3);
                 if(CaseRepoWorkReq!=null){
                     txtCaseVolunteerDate.setText(CaseRepoWorkReq.getRequestDate().toString());
                     if(CaseRepoWorkReq.getReceiver()==null){
                         txtCaseVolunteer.setText("Not Assigned");
                     }else{
                         txtCaseVolunteer.setText(CaseRepoWorkReq.getReceiver().toString());
                     }
                     txtCaseVolunteerStatus.setText(CaseRepoWorkReq.getStatus());
                     
                        if(CaseRepoWorkReq.getTrainingCoachWorkRequest()!=null){
                            TrainingCoachWorkRequest D = CaseRepoWorkReq.getTrainingCoachWorkRequest(); 
                            txtDoctorDate.setText(D.getRequestDate().toString());
                        if(D.getReceiver()==null){
                            txtDoctor.setText("Not Assigned");
                        }else{
                            txtDoctor.setText(D.getReceiver().toString());
                        }
                        txtDoctorStatus.setText(D.getStatus());
                        }else{
                            txtDoctorDate.setText("-");
                            txtDoctor.setText("-");
                            txtDoctorStatus.setText("-");
                        }
                        
                        if(CaseRepoWorkReq.getFundAllocatorWorkRequest()!=null){
                            FundAllocatorWorkRequest C = CaseRepoWorkReq.getFundAllocatorWorkRequest(); 
                            txtCounsellorDate.setText(C.getRequestDate().toString());
                        if(C.getReceiver()==null){
                            txtCOunsellor.setText("Not Assigned");
                        }else{
                            txtCOunsellor.setText(C.getReceiver().toString());
                        }
                        txtCounsellorStatus.setText(C.getStatus());
                        }else{
                            txtCounsellorDate.setText("-");
                            txtCOunsellor.setText("-");
                            txtCounsellorStatus.setText("-");
                        }
                        
                        if(CaseRepoWorkReq.getMentalHealthCoachWorkRequest()!=null){
                            MentalHealthCoachWorkRequest P = CaseRepoWorkReq.getMentalHealthCoachWorkRequest(); 
                            txtlPsychDate.setText(P.getRequestDate().toString());
                        if(P.getReceiver()==null){
                            txtPsych.setText("Not Assigned");
                        }else{
                            txtPsych.setText(P.getReceiver().toString());
                        }
                        txtPsychStatus.setText(P.getStatus());
                        }else{
                            txtlPsychDate.setText("-");
                            txtPsych.setText("-");
                            txtPsychStatus.setText("-");
                        }
                        
                        if(CaseRepoWorkReq.getInsuranceAgentWorkRequest()!=null){
                            InsuranceAgentWorkRequest L = CaseRepoWorkReq.getInsuranceAgentWorkRequest(); 
                            txtLawyerDate.setText(L.getRequestDate().toString());
                        if(L.getReceiver()==null){
                            txtLawyer.setText("Not Assigned");
                        }else{
                            txtLawyer.setText(L.getReceiver().toString());
                        }
                        txtLawyerStatus.setText(L.getStatus());
                        }else{
                            txtLawyerDate.setText("-");
                            txtLawyer.setText("-");
                            txtLawyerStatus.setText("-");
                        }
                 }
                     
                 
             }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaseVolunteer;
    private javax.swing.JLabel lblCounsellor;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoc;
    private javax.swing.JLabel lblLawyer;
    private javax.swing.JLabel lblPsych;
    private javax.swing.JLabel lblReceiver;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tableCases;
    private javax.swing.JLabel txtCOunsellor;
    private javax.swing.JLabel txtCaseVolunteer;
    private javax.swing.JLabel txtCaseVolunteerDate;
    private javax.swing.JLabel txtCaseVolunteerStatus;
    private javax.swing.JLabel txtCounsellorDate;
    private javax.swing.JLabel txtCounsellorStatus;
    private javax.swing.JLabel txtDoctor;
    private javax.swing.JLabel txtDoctorDate;
    private javax.swing.JLabel txtDoctorStatus;
    private javax.swing.JLabel txtLawyer;
    private javax.swing.JLabel txtLawyerDate;
    private javax.swing.JLabel txtLawyerStatus;
    private javax.swing.JLabel txtPsych;
    private javax.swing.JLabel txtPsychStatus;
    private javax.swing.JLabel txtlPsychDate;
    // End of variables declaration//GEN-END:variables
}
