/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.YouthSportsRecruitingManager;

import javax.swing.JPanel; 
import business.EcoSystem;
import business.Network.Network;
import business.Organization.TalentRecruitmentOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.TalentScoutWorkRequest;
import business.WorkQueue.FundAllocatorWorkRequest;
import business.WorkQueue.TrainingCoachWorkRequest;
import business.WorkQueue.InsuranceAgentWorkRequest;
import business.WorkQueue.MentalHealthCoachWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author puranjaimendiratta
 */
public class EnrollmentRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentRequestJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    Organization organization; 
    UserAccount userAccount;
    Network network; 
    public EnrollmentRequestJPanel(JPanel userProcessContainer, EcoSystem system, Organization organization,UserAccount userAccount,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.organization=(TalentRecruitmentOrganization)organization;
        this.userAccount=userAccount;
        this.network = network;
        
        popTable();
        lblReceiver.setVisible(false);
        lblStatus.setVisible(false);
        lblDate.setVisible(false);
        lblDoctor.setVisible(false);
        lblCounsellar.setVisible(false);
        lblLawyer.setVisible(false);
        lblPsychiatrist.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCaseReq = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaseRequest = new javax.swing.JTable();
        btnAssignRequest = new javax.swing.JButton();
        btnViewCaseReport = new javax.swing.JButton();
        btnCheckStatus = new javax.swing.JButton();
        txtPsyhDate = new javax.swing.JLabel();
        txtLawyerReceiver = new javax.swing.JLabel();
        txtLawyerDate = new javax.swing.JLabel();
        txtCousellarStatus = new javax.swing.JLabel();
        txtCounsellarReceiver = new javax.swing.JLabel();
        txtCounsellarDate = new javax.swing.JLabel();
        lblPsychiatrist = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblLawyer = new javax.swing.JLabel();
        txtPsychStatus = new javax.swing.JLabel();
        txtLawyerStatus = new javax.swing.JLabel();
        lblCounsellar = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblReceiver = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtPsychReceiver = new javax.swing.JLabel();
        txtDocStatus = new javax.swing.JLabel();
        txtDocReceiver = new javax.swing.JLabel();
        txtDoctorDate = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCaseReq.setBackground(new java.awt.Color(255, 255, 255));
        lblCaseReq.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        lblCaseReq.setForeground(new java.awt.Color(255, 146, 1));
        lblCaseReq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCaseReq.setText("Enrollment Requests");
        lblCaseReq.setToolTipText("");
        lblCaseReq.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblCaseReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 879, -1));

        tblCaseRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name ", "Location", "Status", "Assigned To"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCaseRequest);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 490, 150));

        btnAssignRequest.setBackground(new java.awt.Color(255, 146, 1));
        btnAssignRequest.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnAssignRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignRequest.setText("Assign Request");
        btnAssignRequest.setBorderPainted(false);
        btnAssignRequest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAssignRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAssignRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAssignRequestMouseExited(evt);
            }
        });
        btnAssignRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignRequestActionPerformed(evt);
            }
        });
        jPanel2.add(btnAssignRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 170, 42));

        btnViewCaseReport.setBackground(new java.awt.Color(255, 146, 1));
        btnViewCaseReport.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnViewCaseReport.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCaseReport.setText("View Enrollment Report");
        btnViewCaseReport.setBorderPainted(false);
        btnViewCaseReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnViewCaseReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewCaseReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewCaseReportMouseExited(evt);
            }
        });
        btnViewCaseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCaseReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewCaseReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, 38));

        btnCheckStatus.setBackground(new java.awt.Color(255, 146, 1));
        btnCheckStatus.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnCheckStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckStatus.setText("Check Status");
        btnCheckStatus.setBorderPainted(false);
        btnCheckStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCheckStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckStatusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckStatusMouseExited(evt);
            }
        });
        btnCheckStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckStatusActionPerformed(evt);
            }
        });
        jPanel2.add(btnCheckStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 143, 42));
        jPanel2.add(txtPsyhDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 420, 93, 26));
        jPanel2.add(txtLawyerReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 100, 24));
        jPanel2.add(txtLawyerDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 94, 27));
        jPanel2.add(txtCousellarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 126, 32));
        jPanel2.add(txtCounsellarReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 126, 29));
        jPanel2.add(txtCounsellarDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 118, 27));

        lblPsychiatrist.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblPsychiatrist.setForeground(new java.awt.Color(255, 146, 1));
        lblPsychiatrist.setText("Health Coach");
        jPanel2.add(lblPsychiatrist, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, -1, -1));

        lblDoctor.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDoctor.setForeground(new java.awt.Color(255, 146, 1));
        lblDoctor.setText("Training Coach");
        jPanel2.add(lblDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 110, -1));

        lblLawyer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblLawyer.setForeground(new java.awt.Color(255, 146, 1));
        lblLawyer.setText("Insurance Agent");
        jPanel2.add(lblLawyer, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 120, -1));
        jPanel2.add(txtPsychStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 500, 92, 32));
        jPanel2.add(txtLawyerStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 100, 30));

        lblCounsellar.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblCounsellar.setForeground(new java.awt.Color(255, 146, 1));
        lblCounsellar.setText("Fund Allocator");
        jPanel2.add(lblCounsellar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 110, -1));

        lblStatus.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(61, 64, 91));
        lblStatus.setText("Status:");
        jPanel2.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 100, 32));

        lblReceiver.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblReceiver.setForeground(new java.awt.Color(61, 64, 91));
        lblReceiver.setText("Assigned To:");
        jPanel2.add(lblReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 104, 28));

        lblDate.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(61, 64, 91));
        lblDate.setText("Date:");
        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 104, 20));
        jPanel2.add(txtPsychReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 460, 93, 28));
        jPanel2.add(txtDocStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 117, 32));
        jPanel2.add(txtDocReceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 117, 29));
        jPanel2.add(txtDoctorDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 122, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignRequestMouseEntered
        btnAssignRequest.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignRequestMouseEntered

    private void btnAssignRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAssignRequestMouseExited
        btnAssignRequest.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignRequestMouseExited

    private void btnAssignRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignRequestActionPerformed
        try{
            int i=1;
        if(i<5)
        {
            int selectedRow = tblCaseRequest.getSelectedRow();

            if (selectedRow < 0){
                return;
            }

            WorkRequest request = (TalentScoutWorkRequest)tblCaseRequest.getValueAt(selectedRow, 2);
            request.setReceiver(userAccount);
            request.setStatus("Accepted");

            popTable();
            i++;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Only 4 cases can be handled");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please select any one row from table");
        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAssignRequestActionPerformed

    private void btnViewCaseReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCaseReportMouseEntered
        btnViewCaseReport.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCaseReportMouseEntered

    private void btnViewCaseReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewCaseReportMouseExited
        btnViewCaseReport.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewCaseReportMouseExited

    private void btnViewCaseReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCaseReportActionPerformed
        // TODO add your handling code here:
        try{
            int selectedRow = tblCaseRequest.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        TalentScoutWorkRequest request = (TalentScoutWorkRequest)tblCaseRequest.getValueAt(selectedRow, 2);

        if (request.getReceiver()!=userAccount){
            JOptionPane.showMessageDialog(this, "You cannot view the report of the case. Access Denied.");
        }else{

            EnrollmentFormRJPanel caseReportJPanel = new EnrollmentFormRJPanel(userProcessContainer,system,request,userAccount,network);
            userProcessContainer.add("caseReportJPanel", caseReportJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            /*CaseReportJPanel casereportJPanel=new CaseReportJPanel(userProcessContainer,system,request);
            casereportJPanel.setVisible(true);*/
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please select any one row from table");
        }
    }//GEN-LAST:event_btnViewCaseReportActionPerformed

    private void btnCheckStatusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckStatusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckStatusMouseExited

    private void btnCheckStatusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckStatusMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckStatusMouseEntered

    private void btnCheckStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckStatusActionPerformed
        // TODO add your handling code here:
        try{
            int selectedRow = tblCaseRequest.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        if (selectedRow >= 0) {
            lblReceiver.setVisible(true);
            lblStatus.setVisible(true);
            lblDate.setVisible(true);
            lblDoctor.setVisible(true);
            lblCounsellar.setVisible(true);
            lblLawyer.setVisible(true);
            lblPsychiatrist.setVisible(true);
            TalentScoutWorkRequest  CRWorkReq  = (TalentScoutWorkRequest) tblCaseRequest.getValueAt(selectedRow, 2);

            if(CRWorkReq.getTrainingCoachWorkRequest()!=null){
                TrainingCoachWorkRequest D = CRWorkReq.getTrainingCoachWorkRequest();
                txtDoctorDate.setText(D.getRequestDate().toString());
                if(D.getReceiver()==null){
                    txtDocReceiver.setText("Not Assigned");
                }else{
                    txtDocReceiver.setText(D.getReceiver().toString());
                }
                txtDocStatus.setText(D.getStatus());
            }else{
                txtDoctorDate.setText("-");
                txtDocReceiver.setText("-");
                txtDocStatus.setText("-");
            }

            if(CRWorkReq.getFundAllocatorWorkRequest()!=null){
                FundAllocatorWorkRequest C = CRWorkReq.getFundAllocatorWorkRequest();
                txtCounsellarDate.setText(C.getRequestDate().toString());
                if(C.getReceiver()==null){
                    txtCounsellarReceiver.setText("Not Assigned");
                }else{
                    txtCounsellarReceiver.setText(C.getReceiver().toString());
                }
                txtCousellarStatus.setText(C.getStatus());
            }else{
                txtCounsellarDate.setText("-");
                txtCounsellarReceiver.setText("-");
                txtCousellarStatus.setText("-");
            }

            if(CRWorkReq.getMentalHealthCoachWorkRequest()!=null){
                MentalHealthCoachWorkRequest P = CRWorkReq.getMentalHealthCoachWorkRequest();
                txtPsyhDate.setText(P.getRequestDate().toString());
                if(P.getReceiver()==null){
                    txtPsychReceiver.setText("Not Assigned");
                }else{
                    txtPsychReceiver.setText(P.getReceiver().toString());
                }
                txtPsychStatus.setText(P.getStatus());
            }else{
                txtPsychStatus.setText("-");
                txtPsyhDate.setText("-");
                txtPsychReceiver.setText("-");
            }

            if(CRWorkReq.getInsuranceAgentWorkRequest()!=null){
                InsuranceAgentWorkRequest L = CRWorkReq.getInsuranceAgentWorkRequest();
                txtLawyerDate.setText(L.getRequestDate().toString());
                if(L.getReceiver()==null){
                    txtLawyerReceiver.setText("Not Assigned");
                }else{
                    txtLawyerReceiver.setText(L.getReceiver().toString());
                }
                txtLawyerStatus.setText(L.getStatus());
            }else{
                txtLawyerDate.setText("-");
                txtLawyerReceiver.setText("-");
                txtLawyerStatus.setText("-");
            }

        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please select any one row from table");
        }
    }//GEN-LAST:event_btnCheckStatusActionPerformed
    
    private void popTable() {
        
        DefaultTableModel model= (DefaultTableModel) tblCaseRequest.getModel();
        Object[] row=new Object[4];
        model.setRowCount(0);
        
         for(TalentScoutWorkRequest request : organization.getWorkQueue().getTalentScoutWorkRequestList())
         {
         
            row[0] = request.getChildName();
            row[1] = request.getAddress();
            row[2] = request;
            if (request.getReceiver()==null){
                row[3] = "Not Assigned";
            }else{
                row[3] = request.getReceiver();
            }
         
            
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignRequest;
    private javax.swing.JButton btnCheckStatus;
    private javax.swing.JButton btnViewCaseReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaseReq;
    private javax.swing.JLabel lblCounsellar;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblLawyer;
    private javax.swing.JLabel lblPsychiatrist;
    private javax.swing.JLabel lblReceiver;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblCaseRequest;
    private javax.swing.JLabel txtCounsellarDate;
    private javax.swing.JLabel txtCounsellarReceiver;
    private javax.swing.JLabel txtCousellarStatus;
    private javax.swing.JLabel txtDocReceiver;
    private javax.swing.JLabel txtDocStatus;
    private javax.swing.JLabel txtDoctorDate;
    private javax.swing.JLabel txtLawyerDate;
    private javax.swing.JLabel txtLawyerReceiver;
    private javax.swing.JLabel txtLawyerStatus;
    private javax.swing.JLabel txtPsychReceiver;
    private javax.swing.JLabel txtPsychStatus;
    private javax.swing.JLabel txtPsyhDate;
    // End of variables declaration//GEN-END:variables
}
