/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.YouthSportsRecruitingManager;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.SportsFundOrganization;
import business.Organization.MentalHealthOrganization;
import business.Organization.PhysicalTrainingOrganization;
import business.Organization.HealthOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.FundAllocatorWorkRequest;
import business.WorkQueue.TrainingCoachWorkRequest;
import business.WorkQueue.MentalHealthCoachWorkRequest;
import business.WorkQueue.TalentScoutWorkRequest;
import business.WorkQueue.Child;
import business.WorkQueue.Children;
import business.WorkQueue.InsuranceAgentWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author puranjaimendiratta
 */
public class EnrollmentFormRJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentFormRJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    TalentScoutWorkRequest request;
    UserAccount userAccount;
    Network network;
    public EnrollmentFormRJPanel(JPanel userProcessContainer, EcoSystem system, TalentScoutWorkRequest request,UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.request = request;
        this.userAccount = userAccount;
        this.network = network;
        PopulateInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblDate = new javax.swing.JPanel();
        lblVictimName = new javax.swing.JLabel();
        lblRelation = new javax.swing.JLabel();
        lblTypeofAssault = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        timejLabel = new javax.swing.JLabel();
        lblMoreDetail = new javax.swing.JLabel();
        lblNameSuspect = new javax.swing.JLabel();
        txtVictimName = new javax.swing.JTextField();
        txtNameofSuspect = new javax.swing.JTextField();
        txtMoreDetails = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtVolunteerName = new javax.swing.JTextField();
        txtTypeofAssault = new javax.swing.JTextField();
        txtDateofIncident = new javax.swing.JTextField();
        btnReqLawyer = new javax.swing.JButton();
        btnReqDoc = new javax.swing.JButton();
        btnReqPsych = new javax.swing.JButton();
        btnReqCounsellar = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblVictimInfo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDate.setBackground(new java.awt.Color(255, 255, 255));
        lblDate.setForeground(new java.awt.Color(255, 255, 255));

        lblVictimName.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblVictimName.setText("Child name : ");

        lblRelation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblRelation.setText("Gender :");

        lblTypeofAssault.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblTypeofAssault.setText("Sport :");

        lblLocation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblLocation.setText("Address :");

        timejLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        timejLabel.setText("Date of Enrollment :");

        lblMoreDetail.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblMoreDetail.setText("Parent Name :");

        lblNameSuspect.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblNameSuspect.setText("Weight : ");

        txtVictimName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVictimNameActionPerformed(evt);
            }
        });

        txtNameofSuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameofSuspectActionPerformed(evt);
            }
        });

        txtMoreDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoreDetailsActionPerformed(evt);
            }
        });

        txtVolunteerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolunteerNameActionPerformed(evt);
            }
        });

        txtTypeofAssault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeofAssaultActionPerformed(evt);
            }
        });

        btnReqLawyer.setBackground(new java.awt.Color(255, 146, 1));
        btnReqLawyer.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqLawyer.setForeground(new java.awt.Color(255, 255, 255));
        btnReqLawyer.setText("Insurance Agent");
        btnReqLawyer.setBorderPainted(false);
        btnReqLawyer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqLawyerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqLawyerMouseExited(evt);
            }
        });
        btnReqLawyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqLawyerActionPerformed(evt);
            }
        });

        btnReqDoc.setBackground(new java.awt.Color(255, 146, 1));
        btnReqDoc.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnReqDoc.setText("Training Coach");
        btnReqDoc.setBorderPainted(false);
        btnReqDoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqDocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqDocMouseExited(evt);
            }
        });
        btnReqDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqDocActionPerformed(evt);
            }
        });

        btnReqPsych.setBackground(new java.awt.Color(255, 146, 1));
        btnReqPsych.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqPsych.setForeground(new java.awt.Color(255, 255, 255));
        btnReqPsych.setText("Mental Health Coach");
        btnReqPsych.setBorderPainted(false);
        btnReqPsych.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqPsychMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqPsychMouseExited(evt);
            }
        });
        btnReqPsych.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqPsychActionPerformed(evt);
            }
        });

        btnReqCounsellar.setBackground(new java.awt.Color(255, 146, 1));
        btnReqCounsellar.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnReqCounsellar.setForeground(new java.awt.Color(255, 255, 255));
        btnReqCounsellar.setText("Fund Allocator");
        btnReqCounsellar.setBorderPainted(false);
        btnReqCounsellar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReqCounsellarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReqCounsellarMouseExited(evt);
            }
        });
        btnReqCounsellar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqCounsellarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblDateLayout = new javax.swing.GroupLayout(lblDate);
        lblDate.setLayout(lblDateLayout);
        lblDateLayout.setHorizontalGroup(
            lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblDateLayout.createSequentialGroup()
                        .addComponent(btnReqLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblDateLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnReqDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReqPsych, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReqCounsellar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(lblDateLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtNameofSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(lblDateLayout.createSequentialGroup()
                        .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(lblDateLayout.createSequentialGroup()
                                    .addComponent(lblNameSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(78, 78, 78))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblDateLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(lblVictimName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lblDateLayout.createSequentialGroup()
                                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(timejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTypeofAssault, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRelation)))
                                .addGap(68, 68, 68)
                                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateofIncident, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVictimName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTypeofAssault, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lblDateLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblMoreDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(txtMoreDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(477, Short.MAX_VALUE))))
        );
        lblDateLayout.setVerticalGroup(
            lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblDateLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVictimName)
                    .addComponent(txtVictimName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRelation)
                    .addComponent(txtVolunteerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTypeofAssault)
                    .addComponent(txtTypeofAssault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLocation))
                .addGap(23, 23, 23)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDateofIncident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMoreDetail)
                    .addComponent(txtMoreDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameSuspect)
                    .addComponent(txtNameofSuspect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(lblDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReqLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReqDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReqPsych, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReqCounsellar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel2.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 62, 850, -1));

        btnBack.setBackground(new java.awt.Color(255, 146, 1));
        btnBack.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 14, 82, -1));

        lblVictimInfo.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        lblVictimInfo.setForeground(new java.awt.Color(255, 146, 1));
        lblVictimInfo.setText("Child Information");
        jPanel2.add(lblVictimInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 14, 230, 42));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 20, 940, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVictimNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVictimNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVictimNameActionPerformed

    private void txtNameofSuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameofSuspectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameofSuspectActionPerformed

    private void txtVolunteerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolunteerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolunteerNameActionPerformed

    private void txtTypeofAssaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeofAssaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeofAssaultActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //CaseVolunteerPJPanel sysAdminwjp = (CaseVolunteerPJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);         // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnReqLawyerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqLawyerMouseEntered
        btnReqCounsellar.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqLawyerMouseEntered

    private void btnReqLawyerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqLawyerMouseExited
        btnReqLawyer.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqLawyerMouseExited

    private void btnReqLawyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqLawyerActionPerformed
        InsuranceAgentWorkRequest legalawyerequest = new InsuranceAgentWorkRequest();
        legalawyerequest.setStatus("Waiting");
        legalawyerequest.setSender(userAccount);
        legalawyerequest.setTalentScoutWorkRequest(request);
        legalawyerequest.getTalentScoutWorkRequest().setInsuranceAgentWorkRequest(legalawyerequest);
        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.Insurance);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof HealthOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getInsuranceAgentWorkRequestList().add(legalawyerequest);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getInsuranceAgentWorkRequestList().add(legalawyerequest);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Insurance Agent.");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqLawyerActionPerformed

    private void btnReqCounsellarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCounsellarMouseEntered
        btnReqCounsellar.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqCounsellarMouseEntered

    private void btnReqCounsellarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqCounsellarMouseExited
        btnReqCounsellar.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqCounsellarMouseExited

    private void btnReqCounsellarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqCounsellarActionPerformed
        FundAllocatorWorkRequest counsellarreq = new FundAllocatorWorkRequest();
        counsellarreq.setStatus("Waiting");
        counsellarreq.setSender(userAccount);
        counsellarreq.setHswr(request);
        counsellarreq.getHswr().setFundAllocatorWorkRequest(counsellarreq);

        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.NGO);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof SportsFundOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getFundAllocatorWorkRequestList().add(counsellarreq);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getFundAllocatorWorkRequestList().add(counsellarreq);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Fund Allocator");
        // TODO add your handling code here:

    }//GEN-LAST:event_btnReqCounsellarActionPerformed

    private void btnReqDocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqDocMouseEntered
        btnReqDoc.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqDocMouseEntered

    private void btnReqDocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqDocMouseExited
        btnReqDoc.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqDocMouseExited

    private void btnReqDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqDocActionPerformed
        TrainingCoachWorkRequest docrequest = new TrainingCoachWorkRequest();
        docrequest.setStatus("Waiting");
        docrequest.setSender(userAccount);
        docrequest.setTalentScoutWorkRequest(request);
        docrequest.getTalentScoutWorkRequest().setTrainingCoachWorkRequest(docrequest);

        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.HealthWellBeing);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PhysicalTrainingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getTrainingCoachWorkRequestList().add(docrequest);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getTrainingCoachWorkRequestList().add(docrequest);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Training Coach.");
    }//GEN-LAST:event_btnReqDocActionPerformed

    private void btnReqPsychMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqPsychMouseEntered
        btnReqPsych.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqPsychMouseEntered

    private void btnReqPsychMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReqPsychMouseExited
        btnReqPsych.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnReqPsychMouseExited

    private void btnReqPsychActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqPsychActionPerformed
        MentalHealthCoachWorkRequest psychrequest = new MentalHealthCoachWorkRequest();
        psychrequest.setStatus("Waiting");
        psychrequest.setSender(userAccount);
        psychrequest.setTalentScoutWorkRequest(request);
        psychrequest.getTalentScoutWorkRequest().setMentalHealthWorkRequest(psychrequest);

        Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.HealthWellBeing);
        Organization org = null;
        for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
            System.out.println("ex"+organization.getName());
            if (organization instanceof MentalHealthOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getMentalHealthCoachWorkRequestList().add(psychrequest);
            //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            userAccount.getWrkQue().getMentalHealthCoachWorkRequestList().add(psychrequest);
        }

        JOptionPane.showMessageDialog(null, "Request submitted to Mental Health Coach");
    }//GEN-LAST:event_btnReqPsychActionPerformed

    private void txtMoreDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoreDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoreDetailsActionPerformed
    
    private void PopulateInfo() {
        txtVictimName.setText(request.getChildName());
        txtVolunteerName.setText(request.getGender());
        txtTypeofAssault.setText(request.getSportType());
        txtLocation.setText(request.getAddress());
        txtDateofIncident.setText(request.getDoe().toString());
        txtMoreDetails.setText(request.getParentName());
//       // txtSuspect.setText(request.getHeight());
        txtNameofSuspect.setText(request.getWeight());
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReqCounsellar;
    private javax.swing.JButton btnReqDoc;
    private javax.swing.JButton btnReqLawyer;
    private javax.swing.JButton btnReqPsych;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel lblDate;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMoreDetail;
    private javax.swing.JLabel lblNameSuspect;
    private javax.swing.JLabel lblRelation;
    private javax.swing.JLabel lblTypeofAssault;
    private javax.swing.JLabel lblVictimInfo;
    private javax.swing.JLabel lblVictimName;
    private javax.swing.JLabel timejLabel;
    private javax.swing.JTextField txtDateofIncident;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMoreDetails;
    private javax.swing.JTextField txtNameofSuspect;
    private javax.swing.JTextField txtTypeofAssault;
    private javax.swing.JTextField txtVictimName;
    private javax.swing.JTextField txtVolunteerName;
    // End of variables declaration//GEN-END:variables
}
